version: 2.1

executors:
  ngx-build-plugin:
    working_directory: ~/ngx-build-plugin
    docker:
      - image: circleci/node:8.15.0

jobs:
  build:
    executor: ngx-build-plugin
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-workspace-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-workspace-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Build Package
          command: yarn build
      - persist_to_workspace:
          root: ~/ngx-build-plugin
          paths: .

  test:
    executor: ngx-build-plugin
    steps:
      - attach_workspace:
          at: ~/ngx-build-plugin
      - run:
          name: Test Package
          command: yarn test
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: yarn-workspace-{{ checksum "yarn.lock" }}
          paths:
            - build/.jest-cache

  deploy:
    executor: ngx-build-plugin
    steps:
      - attach_workspace:
          at: ~/ngx-build-plugin
      - run:
          name: Authenticate With Registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish Package
          command: npm publish build/package --access public

workflows:
  version: 2.1

  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
