version: 2.1

executors:
  build-executor:
    working_directory: ~/ngx-build-plugin
    docker:
      - image: circleci/node:8.15.0

jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-workspace-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --no-progress --frozen-lockfile
      - save_cache:
          key: yarn-workspace-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Build Package
          command: yarn build
      - persist_to_workspace:
          root: ~/ngx-build-plugin
          paths: .

  test:
    executor: build-executor
    steps:
      - attach_workspace:
          at: ~/ngx-build-plugin
      - run:
          name: Test Package
          command: yarn test
      - store_test_results:
          path: ./build/test-results
      - store_artifacts:
          path: ./build/test-results

  deploy:
    executor: build-executor
    steps:
      - attach_workspace:
          at: ~/ngx-build-plugin
      - run:
          name: Authenticate With Registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish Package
          command: npm publish ./build/package --access public

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
